### ISSUE TITLE
make install

### ISSUE THREAD

**Issue by dingguodong-826** [alexandrosstergiou/SoftPool#19] opened 2021-01-19 05:57 UTC
Hello, when I run make install, I get the following error:
![image](https://user-images.githubusercontent.com/57715990/104993717-36568e80-5a5e-11eb-927e-e36daa7eab85.png)
![image](https://user-images.githubusercontent.com/57715990/104993752-43737d80-5a5e-11eb-88d4-3b5775b33c9d.png)
thank you

**Comment by alexandrosstergiou** [comment] 2021-01-19 08:45
Hi @dingguodong-826 ,

This is a duplicate of #11 . It is basically based on your PyTorch and CUDA versions. Creating a new environment should fix it.

Best,
Alex

**Closed as completed by alexandrosstergiou** 2021-01-19 08:45 UTC
