### ISSUE TITLE
100+ errors detected in the compilation of softpool_cuda_kernel.cu

### ISSUE THREAD

**Issue by wlcosta** [alexandrosstergiou/SoftPool#34] opened 2021-04-16 18:35 UTC
Hey. I am getting a few errors during the installation process.
Into the `SoftPool/pytorch` folder, I run `make install` as explained in the README file, and during the process, three errors show up in the console repeatedly:

```
CUDA/softpool_cuda_kernel.cu(252): error: type name is not allowed
CUDA/softpool_cuda_kernel.cu(252): error: expected an expression
CUDA/softpool_cuda_kernel.cu(252): error: a pointer to a bound function may only be used to call the function
```

And then:

```
Error limit reached.
100 errors detected in the compilation of "CUDA/softpool_cuda_kernel.cu".
Compilation terminated.
error: command '/usr/local/cuda-11.3/bin/nvcc' failed with exit status 1
Makefile:2: recipe for target 'install' failed
make: *** [install] Error 1
```

For quick inspection, here are the lines that are causing the error (at least the first 100 of them). It looks like the issue is with `AT_DISPATCH_FLOATING_TYPES_AND_HALF`:

https://github.com/alexandrosstergiou/SoftPool/blob/f0a342f76afdb9b25f1fec8e4cb4b6bba35e8684/pytorch/CUDA/softpool_cuda_kernel.cu#L252-L264

https://github.com/alexandrosstergiou/SoftPool/blob/f0a342f76afdb9b25f1fec8e4cb4b6bba35e8684/pytorch/CUDA/softpool_cuda_kernel.cu#L280-L294

https://github.com/alexandrosstergiou/SoftPool/blob/f0a342f76afdb9b25f1fec8e4cb4b6bba35e8684/pytorch/CUDA/softpool_cuda_kernel.cu#L312-L327

https://github.com/alexandrosstergiou/SoftPool/blob/f0a342f76afdb9b25f1fec8e4cb4b6bba35e8684/pytorch/CUDA/softpool_cuda_kernel.cu#L566-L581

https://github.com/alexandrosstergiou/SoftPool/blob/f0a342f76afdb9b25f1fec8e4cb4b6bba35e8684/pytorch/CUDA/softpool_cuda_kernel.cu#L600-L616

I have tried different CUDA versions (9.0, 10.2, 11.3) and different GCC/G++ versions (5, 8 and 9), but no success. I am using Ubuntu 16.04 with an RTX 2080 Ti.

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-23ubuntu1~16.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-oatUX7/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-23ubuntu1~16.04)
```

Thanks!

**Comment by alexandrosstergiou** [comment] 2021-04-27 06:50
Hi @wlcosta ,

Since you have tried a lot of CUDA and g++ versions together, you should check your CUDA compiler compatibility [this table](https://gist.github.com/ax3l/9489132). 

As I cannot reproduce the problem, since it's specific to the compiler that you're using, you can check [this solution](https://devtalk.blender.org/t/wrong-gcc-version-for-cuda-linux-how-to-solve/12773) for resolving issues between GCC versions and CUDA. Alternatively, you can also build with [`--ccbin`](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#file-and-path-specifications-compiler-bindir) which may help avoid the current incompatibility issues that you have.

Best,
Alex

**Comment by alexandrosstergiou** [comment] 2021-05-17 16:30
Closing this issue for now. Will be interested to get updates, in case that you are able to solve the problem, to include them as a possible solution when other people have installation issues.

Best.
Alex

**Closed as completed by alexandrosstergiou** 2021-05-17 16:30 UTC
